packages:
  - apps/*
  - packages/*
  - packages/development/*

onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - better-sqlite3
  - core-js
  - esbuild
  - oxc-resolver
  - puppeteer
  - sqlite3
  - style-dictionary
