/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiBookmarksRouteImport } from './routes/api/bookmarks'
import { Route as ApiAuthTestSessionRouteImport } from './routes/api/auth/test-session'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedBookmarksNewRouteImport } from './routes/_protected/bookmarks/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiBookmarksRoute = ApiBookmarksRouteImport.update({
  id: '/api/bookmarks',
  path: '/api/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestSessionRoute = ApiAuthTestSessionRouteImport.update({
  id: '/api/auth/test-session',
  path: '/api/auth/test-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBookmarksNewRoute = ProtectedBookmarksNewRouteImport.update({
  id: '/bookmarks/new',
  path: '/bookmarks/new',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/login': typeof LoginRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/bookmarks/new': typeof ProtectedBookmarksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/test-session': typeof ApiAuthTestSessionRoute
}
export interface FileRoutesByTo {
  '/auth-error': typeof AuthErrorRoute
  '/login': typeof LoginRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/': typeof ProtectedIndexRoute
  '/bookmarks/new': typeof ProtectedBookmarksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/test-session': typeof ApiAuthTestSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/login': typeof LoginRoute
  '/api/bookmarks': typeof ApiBookmarksRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/bookmarks/new': typeof ProtectedBookmarksNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/test-session': typeof ApiAuthTestSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-error'
    | '/login'
    | '/api/bookmarks'
    | '/bookmarks/new'
    | '/api/auth/$'
    | '/api/auth/providers'
    | '/api/auth/test-session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth-error'
    | '/login'
    | '/api/bookmarks'
    | '/'
    | '/bookmarks/new'
    | '/api/auth/$'
    | '/api/auth/providers'
    | '/api/auth/test-session'
  id:
    | '__root__'
    | '/_protected'
    | '/auth-error'
    | '/login'
    | '/api/bookmarks'
    | '/_protected/'
    | '/_protected/bookmarks/new'
    | '/api/auth/$'
    | '/api/auth/providers'
    | '/api/auth/test-session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  LoginRoute: typeof LoginRoute
  ApiBookmarksRoute: typeof ApiBookmarksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiAuthTestSessionRoute: typeof ApiAuthTestSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/bookmarks': {
      id: '/api/bookmarks'
      path: '/api/bookmarks'
      fullPath: '/api/bookmarks'
      preLoaderRoute: typeof ApiBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/test-session': {
      id: '/api/auth/test-session'
      path: '/api/auth/test-session'
      fullPath: '/api/auth/test-session'
      preLoaderRoute: typeof ApiAuthTestSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/bookmarks/new': {
      id: '/_protected/bookmarks/new'
      path: '/bookmarks/new'
      fullPath: '/bookmarks/new'
      preLoaderRoute: typeof ProtectedBookmarksNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedBookmarksNewRoute: typeof ProtectedBookmarksNewRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedBookmarksNewRoute: ProtectedBookmarksNewRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  LoginRoute: LoginRoute,
  ApiBookmarksRoute: ApiBookmarksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiAuthTestSessionRoute: ApiAuthTestSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
